
---
- hosts: all
  become: true

  vars:
    grupo_nombre: GRUPO 5
    division: 314
    fecha: "{{ ansible_date_time.date }}"
    distro: "{{ ansible_distribution }}"
    cores: "{{ ansible_processor_cores }}"
    integrantes:
      - { rol: "R1", nombre: "MAURO", apellido: "LAIME", descripcion_rol: "Líder" }
      - { rol: "R2", nombre: "ADRIAN", apellido: "FERRERA", descripcion_rol: "LVM" }
      - { rol: "R3", nombre: "MAURO", apellido: "LAIME", descripcion_rol: "Bash Scripting" }
      - { rol: "R4", nombre: "EMILSE", apellido: "GOMEZ", descripcion_rol: "ANSIBLE" }
      - { rol: "R5", nombre: "CARLA", apellido: "LOPEZ", descripcion_rol: "Docker" }
      - { rol: "R6", nombre: "NICOLAS", apellido: "MARGNI", descripcion_rol: "Verificaciones" }

  pre_tasks:
    - name: "Inicio del playbook"
      debug:
        msg: "Iniciando la ejecución del TP AySO"

  roles:
    - TP_INI
    - Alta_Usuarios_GTGFDF
    - Sudoers_GTGFDF
    - Instala-tools_GTGFDF

  post_tasks:
    - name: "Fin del playbook"
      debug:
        msg: "Finalizó la ejecución del TP AySO"
